//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitathon.org.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int ID { get; set; }
        public int sponsorID { get; set; }
        public decimal amount { get; set; }
        public bool charged { get; set; }
        public bool success { get; set; }
        public string processorTrxID { get; set; }
    
        public virtual sponsor sponsor { get; set; }
    }
}
