//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitathon.org.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitathonDataEntities : DbContext
    {
        public FitathonDataEntities()
            : base("name=FitathonDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<appsetting> appsettings { get; set; }
        public DbSet<donation> donations { get; set; }
        public DbSet<sponsor> sponsors { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<fitevent> fitevents { get; set; }
        public DbSet<participant> participants { get; set; }
    }
}
