//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitathon.org.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant
    {
        public participant()
        {
            this.sponsors = new HashSet<sponsor>();
        }
    
        public int id { get; set; }
        public int userID { get; set; }
        public int eventID { get; set; }
        public int stepsTaken { get; set; }
        public Nullable<int> averageDailySteps { get; set; }
        public string fitbitAuthCode { get; set; }
        public string fitbitAccessToken { get; set; }
        public string fitbitRefreshToken { get; set; }
        public string uniqueID { get; set; }
    
        public virtual fitevent fitevent { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<sponsor> sponsors { get; set; }
    }
}
