//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitathon.org.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponsor
    {
        public sponsor()
        {
            this.donations = new HashSet<donation>();
        }
    
        public int id { get; set; }
        public int userID { get; set; }
        public int participantID { get; set; }
        public string payMethodToken { get; set; }
        public string payMethodCustomerId { get; set; }
        public string payMethodType { get; set; }
        public Nullable<decimal> pledgeAmount { get; set; }
        public Nullable<int> pledgePerSteps { get; set; }
        public Nullable<decimal> donationMax { get; set; }
    
        public virtual ICollection<donation> donations { get; set; }
        public virtual participant participant { get; set; }
        public virtual user user { get; set; }
    }
}
